version: "3.9"

services:
  db:
    image: postgres:15
    container_name: some-postgres
    restart: always
    environment:
      POSTGRES_USER: abril
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: bd
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./bd/schema:/docker-entrypoint-initdb.d

  app:
    build: ./parte1
    container_name: go-app
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://abril:1234@db:5432/bd?sslmode=disable
    ports:
      - "8080:8080"

volumes:
  db_data:

