// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package bd

import (
	"database/sql"
)

type Libro struct {
	ID              int32         `json:"id"`
	Titulo          string        `json:"titulo"`
	Autor           string        `json:"autor"`
	Descripcion     string        `json:"descripcion"`
	Valoracion      sql.NullInt32 `json:"valoracion"`
	Anio            int32         `json:"anio"`
	GeneroPrincipal string        `json:"genero_principal"`
}
